$axure.loadCurrentPage({
  "url":"招聘信息详情页.html",
  "generationDate":new Date(1432258258657.76),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"04c804e2ae9941f1a245591bb72904b5",
    "type":"Axure:Page",
    "name":"招聘信息详情页",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"7f9081f8468e4d1ab1f3be94136fd129",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":110,
              "y":40},
            "size":{
              "width":330,
              "height":450}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e999134b65ce413ab949cc442d05b68b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":110,
                  "y":40},
                "size":{
                  "width":330,
                  "height":450}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/招聘_求职列表/u0.png"}},
{
          "id":"fa32c39bc2ec46aca564bd61932e70e6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFFC9C9C9},
            "location":{
              "x":110,
              "y":40},
            "size":{
              "width":330,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c6d64f5f82f44897994a95273e074966",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9},
                "location":{
                  "x":110,
                  "y":40},
                "size":{
                  "width":330,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/招聘_求职列表/u2.png"}},
{
          "id":"d5752c3c2f5843d4b3049d845f439d66",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":115,
              "y":47},
            "size":{
              "width":9,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e170e9b4cbb64eeea3519c4ad5b4f5be",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":115,
                  "y":47},
                "size":{
                  "width":9,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cb4fa6bd182f4b02a07548e4a8537946",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":118,
              "y":80},
            "size":{
              "width":313,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1bdac1ac7d164006949872ed2690117e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":118,
                  "y":80},
                "size":{
                  "width":313,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1fe0ef28c7bd4a25a3a977af6bd100ea",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":109},
            "size":{
              "width":330,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/招聘_求职列表/u12_line.png"}},
{
          "id":"825cc861e2454b1cbffac2aa6aa55d51",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":124,
              "y":122},
            "size":{
              "width":261,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7af16a8fefed44fc9a4b40117ebb92da",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":124,
                  "y":122},
                "size":{
                  "width":261,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bf8c271852c4440b9a1d84eefefca60d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":115,
              "y":191},
            "size":{
              "width":1,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"585b1679aa8b4230a3fe27d244269b1a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":115,
                  "y":191},
                "size":{
                  "width":1,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"959cdccc3440400ba87532a7f1f368d8",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":223},
            "size":{
              "width":330,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/招聘_求职列表/u12_line.png"}},
{
          "id":"f9317ad5752b4dda868cdcb92cfb82d2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":115,
              "y":233},
            "size":{
              "width":136,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"034a73be306e4e35b0a3615d12e25d86",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":115,
                  "y":233},
                "size":{
                  "width":136,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f68484153d0249ce9f93a652d6aa68ae",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":265},
            "size":{
              "width":330,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/招聘_求职列表/u12_line.png"}},
{
          "id":"d2c6c56076a14ba1aab5d3778d34bdc3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":367,
              "y":96},
            "size":{
              "width":65,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"697ba388c87742d1b307eb7682c83b4a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":367,
                  "y":96},
                "size":{
                  "width":65,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "7f9081f8468e4d1ab1f3be94136fd129":{
      "scriptId":"u0"},
    "e999134b65ce413ab949cc442d05b68b":{
      "scriptId":"u1"},
    "fa32c39bc2ec46aca564bd61932e70e6":{
      "scriptId":"u2"},
    "c6d64f5f82f44897994a95273e074966":{
      "scriptId":"u3"},
    "d5752c3c2f5843d4b3049d845f439d66":{
      "scriptId":"u4"},
    "e170e9b4cbb64eeea3519c4ad5b4f5be":{
      "scriptId":"u5"},
    "cb4fa6bd182f4b02a07548e4a8537946":{
      "scriptId":"u6"},
    "1bdac1ac7d164006949872ed2690117e":{
      "scriptId":"u7"},
    "1fe0ef28c7bd4a25a3a977af6bd100ea":{
      "scriptId":"u8"},
    "825cc861e2454b1cbffac2aa6aa55d51":{
      "scriptId":"u9"},
    "7af16a8fefed44fc9a4b40117ebb92da":{
      "scriptId":"u10"},
    "bf8c271852c4440b9a1d84eefefca60d":{
      "scriptId":"u11"},
    "585b1679aa8b4230a3fe27d244269b1a":{
      "scriptId":"u12"},
    "959cdccc3440400ba87532a7f1f368d8":{
      "scriptId":"u13"},
    "f9317ad5752b4dda868cdcb92cfb82d2":{
      "scriptId":"u14"},
    "034a73be306e4e35b0a3615d12e25d86":{
      "scriptId":"u15"},
    "f68484153d0249ce9f93a652d6aa68ae":{
      "scriptId":"u16"},
    "d2c6c56076a14ba1aab5d3778d34bdc3":{
      "scriptId":"u17"},
    "697ba388c87742d1b307eb7682c83b4a":{
      "scriptId":"u18"}}});