$axure.loadCurrentPage({
  "url":"点击收藏.html",
  "generationDate":new Date(1432258261440.91),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"4577b3b9311e4cfb9eca14f44a298ac8",
    "type":"Axure:Page",
    "name":"点击收藏",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"3f2e3aef69444933a279eb8f505f2023",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":109,
              "y":40},
            "size":{
              "width":330,
              "height":450}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4abc8dde7b474adfaf6e1cb8b0e4d245",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":109,
                  "y":40},
                "size":{
                  "width":330,
                  "height":450}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/招聘_求职列表/u0.png"}},
{
          "id":"98f6c3087ceb4627bcc38956a1081e67",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFFBCBCBC},
            "location":{
              "x":110,
              "y":460},
            "size":{
              "width":328,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3a3c77c9b7ff479d8a6f2bda9bb6e0bc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC},
                "location":{
                  "x":110,
                  "y":460},
                "size":{
                  "width":328,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/产品详情页/u2.png"}},
{
          "id":"77bd2ee091934c6985c828c7e7d0f5c3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFFC9C9C9},
            "location":{
              "x":110,
              "y":40},
            "size":{
              "width":330,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dea7c6a0fdde493ca6da6aadd664ff84",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9},
                "location":{
                  "x":110,
                  "y":40},
                "size":{
                  "width":330,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/招聘_求职列表/u2.png"}},
{
          "id":"c36215300abc4d0db8949f7b7e8af92c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":115,
              "y":47},
            "size":{
              "width":9,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9e34000db87b4de1a907204f32a1b203",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":115,
                  "y":47},
                "size":{
                  "width":9,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f249594855714535ad453bb634e5d634",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":110,
              "y":68},
            "size":{
              "width":330,
              "height":182}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6d58e4847dba4597b3ecb465b4fd470b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":110,
                  "y":68},
                "size":{
                  "width":330,
                  "height":182}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/产品详情页/u8.png"}},
{
          "id":"ff7d49ae9f0d45e78eab70c7bce747a9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":200,
              "y":220},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0321452b76df445e95eeaeae1285bcd6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":200,
                  "y":220},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/产品详情页/u10.png"}},
{
          "id":"e44aa466bbed4db481fecc36eea261d9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":230,
              "y":220},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3561f1a077df4a83ab159a065cdfb1b7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":230,
                  "y":220},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/产品详情页/u10.png"}},
{
          "id":"04a42af7a0cd4333960288094c0e05b9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":260,
              "y":220},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e32abfdaef0d4d04a9cf7de04b22db5c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":260,
                  "y":220},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/产品详情页/u10.png"}},
{
          "id":"64a04190ca6a4de6a44843b881cdbc2b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":290,
              "y":220},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1326c68f041543ed96ab0763d30d2f95",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":290,
                  "y":220},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/产品详情页/u10.png"}},
{
          "id":"691dfddee8be44a191d204acf9bd8a61",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":320,
              "y":220},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"84153183f32d4384b3a7a9754e2b1546",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":320,
                  "y":220},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/产品详情页/u10.png"}},
{
          "id":"c07a7f29ba8942c88136b813417d7602",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":115,
              "y":257},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"628c8871d826434d937ac5675cb2b2c3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":115,
                  "y":257},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f2534160a68147d28025a5cf2966f47d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":115,
              "y":273},
            "size":{
              "width":313,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dc9dbec87d494fb8908c8346db06c3ae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":115,
                  "y":273},
                "size":{
                  "width":313,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f02be8023c244f228edb4a8840f0364f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":115,
              "y":315},
            "size":{
              "width":117,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"04489b509cda40f39c04e0a4f7e64a5d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":115,
                  "y":315},
                "size":{
                  "width":117,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"aa6322bae8b44fe584807b463e568172",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "location":{
              "x":280,
              "y":315},
            "size":{
              "width":95,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1d3d1ff21b584677bbf2caadb70a1769",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "location":{
                  "x":280,
                  "y":315},
                "size":{
                  "width":95,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3eaf2cc08b7e45cc9e7c6123056d76ca",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":115,
              "y":337},
            "size":{
              "width":313,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/产品详情页/u28_line.png"}},
{
          "id":"5a220fd46b2841b4ab8c72a942aff3fa",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFFBCBCBC},
            "location":{
              "x":111,
              "y":343},
            "size":{
              "width":135,
              "height":20},
            "cornerRadiusTopLeft":"1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c9082b6eb8db4e0ca98d7d6a1f9dff65",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC},
                "location":{
                  "x":111,
                  "y":343},
                "size":{
                  "width":135,
                  "height":20},
                "cornerRadiusTopLeft":"1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/产品详情页/u29.png"}},
{
          "id":"6dd6d00ee7044dc48812c37ebe0c0a57",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":246,
              "y":343},
            "size":{
              "width":182,
              "height":20},
            "cornerRadiusTopLeft":"1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6100090c5d554010a36000a63b841e42",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":246,
                  "y":343},
                "size":{
                  "width":182,
                  "height":20},
                "cornerRadiusTopLeft":"1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/产品详情页/u31.png"}},
{
          "id":"27ad4484e38e406c8ebc7d8caa7aa45f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":115,
              "y":367},
            "size":{
              "width":305,
              "height":87}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1245364fb072441a875bfaed86d8fe02",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":115,
                  "y":367},
                "size":{
                  "width":305,
                  "height":87}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/产品详情页/u33.png"}},
{
          "id":"2c44ae19bdb44aa081742d045f3345dd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFFD7D7D7},
            "location":{
              "x":180,
              "y":190},
            "size":{
              "width":200,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"336ad80119bf408baa2ab8b1b1dabe5e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7},
                "location":{
                  "x":180,
                  "y":190},
                "size":{
                  "width":200,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/点击收藏/u35.png"}},
{
          "id":"d99b423c11a743f6b59153eb4b512888",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":590,
              "y":234},
            "size":{
              "width":209,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7cef09aa7d3b46dba1f18adac4625201",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":590,
                  "y":234},
                "size":{
                  "width":209,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "3f2e3aef69444933a279eb8f505f2023":{
      "scriptId":"u0"},
    "4abc8dde7b474adfaf6e1cb8b0e4d245":{
      "scriptId":"u1"},
    "98f6c3087ceb4627bcc38956a1081e67":{
      "scriptId":"u2"},
    "3a3c77c9b7ff479d8a6f2bda9bb6e0bc":{
      "scriptId":"u3"},
    "77bd2ee091934c6985c828c7e7d0f5c3":{
      "scriptId":"u4"},
    "dea7c6a0fdde493ca6da6aadd664ff84":{
      "scriptId":"u5"},
    "c36215300abc4d0db8949f7b7e8af92c":{
      "scriptId":"u6"},
    "9e34000db87b4de1a907204f32a1b203":{
      "scriptId":"u7"},
    "f249594855714535ad453bb634e5d634":{
      "scriptId":"u8"},
    "6d58e4847dba4597b3ecb465b4fd470b":{
      "scriptId":"u9"},
    "ff7d49ae9f0d45e78eab70c7bce747a9":{
      "scriptId":"u10"},
    "0321452b76df445e95eeaeae1285bcd6":{
      "scriptId":"u11"},
    "e44aa466bbed4db481fecc36eea261d9":{
      "scriptId":"u12"},
    "3561f1a077df4a83ab159a065cdfb1b7":{
      "scriptId":"u13"},
    "04a42af7a0cd4333960288094c0e05b9":{
      "scriptId":"u14"},
    "e32abfdaef0d4d04a9cf7de04b22db5c":{
      "scriptId":"u15"},
    "64a04190ca6a4de6a44843b881cdbc2b":{
      "scriptId":"u16"},
    "1326c68f041543ed96ab0763d30d2f95":{
      "scriptId":"u17"},
    "691dfddee8be44a191d204acf9bd8a61":{
      "scriptId":"u18"},
    "84153183f32d4384b3a7a9754e2b1546":{
      "scriptId":"u19"},
    "c07a7f29ba8942c88136b813417d7602":{
      "scriptId":"u20"},
    "628c8871d826434d937ac5675cb2b2c3":{
      "scriptId":"u21"},
    "f2534160a68147d28025a5cf2966f47d":{
      "scriptId":"u22"},
    "dc9dbec87d494fb8908c8346db06c3ae":{
      "scriptId":"u23"},
    "f02be8023c244f228edb4a8840f0364f":{
      "scriptId":"u24"},
    "04489b509cda40f39c04e0a4f7e64a5d":{
      "scriptId":"u25"},
    "aa6322bae8b44fe584807b463e568172":{
      "scriptId":"u26"},
    "1d3d1ff21b584677bbf2caadb70a1769":{
      "scriptId":"u27"},
    "3eaf2cc08b7e45cc9e7c6123056d76ca":{
      "scriptId":"u28"},
    "5a220fd46b2841b4ab8c72a942aff3fa":{
      "scriptId":"u29"},
    "c9082b6eb8db4e0ca98d7d6a1f9dff65":{
      "scriptId":"u30"},
    "6dd6d00ee7044dc48812c37ebe0c0a57":{
      "scriptId":"u31"},
    "6100090c5d554010a36000a63b841e42":{
      "scriptId":"u32"},
    "27ad4484e38e406c8ebc7d8caa7aa45f":{
      "scriptId":"u33"},
    "1245364fb072441a875bfaed86d8fe02":{
      "scriptId":"u34"},
    "2c44ae19bdb44aa081742d045f3345dd":{
      "scriptId":"u35"},
    "336ad80119bf408baa2ab8b1b1dabe5e":{
      "scriptId":"u36"},
    "d99b423c11a743f6b59153eb4b512888":{
      "scriptId":"u37"},
    "7cef09aa7d3b46dba1f18adac4625201":{
      "scriptId":"u38"}}});