$axure.loadCurrentPage({
  "url":"发布招聘.html",
  "generationDate":new Date(1432258258787.76),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"6e5cc452fd9d4cdbb65b55883ff08abf",
    "type":"Axure:Page",
    "name":"发布招聘",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"864b3861ca3c46088e465c869239e30d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":110,
              "y":40},
            "size":{
              "width":330,
              "height":450}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f139682f35714d658499e7d1f7666488",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":110,
                  "y":40},
                "size":{
                  "width":330,
                  "height":450}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/招聘_求职列表/u0.png"}},
{
          "id":"2642c8ae9e9840de9ca95050767b1aee",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFFC9C9C9},
            "location":{
              "x":110,
              "y":40},
            "size":{
              "width":330,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b678792061e340d89cbbab3882f6ab97",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9},
                "location":{
                  "x":110,
                  "y":40},
                "size":{
                  "width":330,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/招聘_求职列表/u2.png"}},
{
          "id":"c92afe24f9db4683b53daad2359c8b03",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":115,
              "y":47},
            "size":{
              "width":9,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0500aff9c58a431e8818e2397d15560c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":115,
                  "y":47},
                "size":{
                  "width":9,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a8153b5833ed421c9009927fc14b8a4f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":115,
              "y":114},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7b870c90af8d4d4a89c493a3f9406d8e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":115,
                  "y":114},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e5865ebc19d54086b74f12f7304ac36b",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":181,
              "y":76},
            "size":{
              "width":248,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"17918b8b7dd644138a283bb7e2154fc2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":358,
              "y":80},
            "size":{
              "width":67,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ba8ee880e32e4d689983b8c9403b68de",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":358,
                  "y":80},
                "size":{
                  "width":67,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"46f06e161111466cbabe3c42ed17d3c6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFFD7D7D7},
            "location":{
              "x":200,
              "y":442},
            "size":{
              "width":171,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0998a4e72ee248fe99a3a0efb51e9b28",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7},
                "location":{
                  "x":200,
                  "y":442},
                "size":{
                  "width":171,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/发布招聘/u11.png"}},
{
          "id":"e458c994f96346c89708e7d726c7a382",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":115,
              "y":80},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7c93dfab399f44db89409f6dba779709",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":115,
                  "y":80},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8942f5752e824c4e9aaec78417db7019",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":181,
              "y":111},
            "size":{
              "width":248,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"d793a85ac5a94ec1a650458ece72e6c6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":115,
              "y":149},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5403ffe1558048a59c52ab2e7a051c05",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":115,
                  "y":149},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"59c9db1c314d4e3f8251360a8716d55b",
          "label":"",
          "type":"textArea",
          "styleType":"textArea",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":181,
              "y":148},
            "size":{
              "width":248,
              "height":171}},
          "adaptiveStyles":{
}},
{
          "id":"f48a830ee957424d901a0cc3ab53f19d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":115,
              "y":355},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9784264e25844c239abdcf9f8a723b5f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":115,
                  "y":355},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fda56049357f47e8b909f65f8f1e7d84",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":115,
              "y":381},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2d37f1fe089946e19eae800f2551ffb5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":115,
                  "y":381},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ac467f1332e0483a878222bbfb2b63ea",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":181,
              "y":346},
            "size":{
              "width":244,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"fc3f03e19a274525a6030d32038d5717",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":181,
              "y":381},
            "size":{
              "width":244,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"a2b910dcbc9a4a0b8a973ae35e7a73f1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":115,
              "y":414},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"935941502d794387872e0a9ed1bfe6f5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":115,
                  "y":414},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"99936895ac774bdab8765f90a034382f",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":181,
              "y":416},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"094a0308973e49d5b94278ccbf639da3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":181,
                  "y":416},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"5e57695a166f43e382825aec56247d52",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":292,
              "y":415},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"307b5ad4caa6405a806349611b1cd276",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":292,
                  "y":415},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]}]}},
  "masters":{
},
  "objectPaths":{
    "864b3861ca3c46088e465c869239e30d":{
      "scriptId":"u0"},
    "f139682f35714d658499e7d1f7666488":{
      "scriptId":"u1"},
    "2642c8ae9e9840de9ca95050767b1aee":{
      "scriptId":"u2"},
    "b678792061e340d89cbbab3882f6ab97":{
      "scriptId":"u3"},
    "c92afe24f9db4683b53daad2359c8b03":{
      "scriptId":"u4"},
    "0500aff9c58a431e8818e2397d15560c":{
      "scriptId":"u5"},
    "a8153b5833ed421c9009927fc14b8a4f":{
      "scriptId":"u6"},
    "7b870c90af8d4d4a89c493a3f9406d8e":{
      "scriptId":"u7"},
    "e5865ebc19d54086b74f12f7304ac36b":{
      "scriptId":"u8"},
    "17918b8b7dd644138a283bb7e2154fc2":{
      "scriptId":"u9"},
    "ba8ee880e32e4d689983b8c9403b68de":{
      "scriptId":"u10"},
    "46f06e161111466cbabe3c42ed17d3c6":{
      "scriptId":"u11"},
    "0998a4e72ee248fe99a3a0efb51e9b28":{
      "scriptId":"u12"},
    "e458c994f96346c89708e7d726c7a382":{
      "scriptId":"u13"},
    "7c93dfab399f44db89409f6dba779709":{
      "scriptId":"u14"},
    "8942f5752e824c4e9aaec78417db7019":{
      "scriptId":"u15"},
    "d793a85ac5a94ec1a650458ece72e6c6":{
      "scriptId":"u16"},
    "5403ffe1558048a59c52ab2e7a051c05":{
      "scriptId":"u17"},
    "59c9db1c314d4e3f8251360a8716d55b":{
      "scriptId":"u18"},
    "f48a830ee957424d901a0cc3ab53f19d":{
      "scriptId":"u19"},
    "9784264e25844c239abdcf9f8a723b5f":{
      "scriptId":"u20"},
    "fda56049357f47e8b909f65f8f1e7d84":{
      "scriptId":"u21"},
    "2d37f1fe089946e19eae800f2551ffb5":{
      "scriptId":"u22"},
    "ac467f1332e0483a878222bbfb2b63ea":{
      "scriptId":"u23"},
    "fc3f03e19a274525a6030d32038d5717":{
      "scriptId":"u24"},
    "a2b910dcbc9a4a0b8a973ae35e7a73f1":{
      "scriptId":"u25"},
    "935941502d794387872e0a9ed1bfe6f5":{
      "scriptId":"u26"},
    "99936895ac774bdab8765f90a034382f":{
      "scriptId":"u27"},
    "094a0308973e49d5b94278ccbf639da3":{
      "scriptId":"u28"},
    "5e57695a166f43e382825aec56247d52":{
      "scriptId":"u29"},
    "307b5ad4caa6405a806349611b1cd276":{
      "scriptId":"u30"}}});