$axure.loadCurrentPage({
  "url":"大家聊,点发布.html",
  "generationDate":new Date(1432258259407.8),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"4ca11de9e182461293f2d415d6248c05",
    "type":"Axure:Page",
    "name":"大家聊,点发布",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"4f1e2c9070af4b14af56a0d0a61ab51d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":110,
              "y":40},
            "size":{
              "width":330,
              "height":450}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"00d6463cb2914ff29b345e79b163d4ce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":110,
                  "y":40},
                "size":{
                  "width":330,
                  "height":450}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/招聘_求职列表/u0.png"}},
{
          "id":"e6a534f568ae4229be38887b2eed51ab",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFFC9C9C9},
            "location":{
              "x":110,
              "y":40},
            "size":{
              "width":330,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2d1bcea326984636bb56dbb9f8a597b4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9},
                "location":{
                  "x":110,
                  "y":40},
                "size":{
                  "width":330,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/招聘_求职列表/u2.png"}},
{
          "id":"918c9089ffc243d9bad800e407bcd28e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":115,
              "y":47},
            "size":{
              "width":9,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"555d1f4b7a2e4649a7dcdc86d7600362",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":115,
                  "y":47},
                "size":{
                  "width":9,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"be7fe2e928234ffb879bdeb8416bb670",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":181,
              "y":76},
            "size":{
              "width":248,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"3edd95fbdeb2413ca5bd6dc64e7df07c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":358,
              "y":80},
            "size":{
              "width":67,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"30783d2a9d5448d49bdd63c5211a920d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":358,
                  "y":80},
                "size":{
                  "width":67,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7a8f703b10814ccbb2bd0b8901263dd0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFFD7D7D7},
            "location":{
              "x":200,
              "y":314},
            "size":{
              "width":171,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"134bf7c2958c4e5882c2b6e66c11cf62",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7},
                "location":{
                  "x":200,
                  "y":314},
                "size":{
                  "width":171,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/发布招聘/u11.png"}},
{
          "id":"38b50911d3454d15b977c4ad6ffe5ab8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":115,
              "y":80},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c41ce2172e704f158170fa7287cb9c4e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":115,
                  "y":80},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a3486e4697d349c7a0e20ab3fd9d7b3c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":115,
              "y":112},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c2f25414f30246fa8354ca5599546df2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":115,
                  "y":112},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f67a3e626f3b452193c31f3e33264d10",
          "label":"",
          "type":"textArea",
          "styleType":"textArea",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":181,
              "y":111},
            "size":{
              "width":248,
              "height":171}},
          "adaptiveStyles":{
}}]}},
  "masters":{
},
  "objectPaths":{
    "4f1e2c9070af4b14af56a0d0a61ab51d":{
      "scriptId":"u0"},
    "00d6463cb2914ff29b345e79b163d4ce":{
      "scriptId":"u1"},
    "e6a534f568ae4229be38887b2eed51ab":{
      "scriptId":"u2"},
    "2d1bcea326984636bb56dbb9f8a597b4":{
      "scriptId":"u3"},
    "918c9089ffc243d9bad800e407bcd28e":{
      "scriptId":"u4"},
    "555d1f4b7a2e4649a7dcdc86d7600362":{
      "scriptId":"u5"},
    "be7fe2e928234ffb879bdeb8416bb670":{
      "scriptId":"u6"},
    "3edd95fbdeb2413ca5bd6dc64e7df07c":{
      "scriptId":"u7"},
    "30783d2a9d5448d49bdd63c5211a920d":{
      "scriptId":"u8"},
    "7a8f703b10814ccbb2bd0b8901263dd0":{
      "scriptId":"u9"},
    "134bf7c2958c4e5882c2b6e66c11cf62":{
      "scriptId":"u10"},
    "38b50911d3454d15b977c4ad6ffe5ab8":{
      "scriptId":"u11"},
    "c41ce2172e704f158170fa7287cb9c4e":{
      "scriptId":"u12"},
    "a3486e4697d349c7a0e20ab3fd9d7b3c":{
      "scriptId":"u13"},
    "c2f25414f30246fa8354ca5599546df2":{
      "scriptId":"u14"},
    "f67a3e626f3b452193c31f3e33264d10":{
      "scriptId":"u15"}}});